### ISSUE TITLE
Lightweight of blockchain

### ISSUE THREAD

**Issue by oltarzewskik** [wisepythagoras/dimoschain#4]
If dimos wants to be "democratic' crypto then we maybe should consider making blockchain as lightweight as possible in order to not discourge some users

**Comment by wisepythagoras** [comment]
Interesting thought. Could you expand?

The thought is exactly that, that it's going to be lightweight. The consensus algorithm will be based on randomness and a pre-shared value to create the a shared and indisputable state.

**Comment by oltarzewskik** [comment]
@wisepythagoras I was thinking about later state of project, about litteraly size in bytes of chain copy (because if somebody wants to "mine" then I think he have to download blockchain on its machine)

Size of blockchain might discourege some small "miners", because of time of downloading blockchain and size that it will take on hard drive.
Also for small miners size of blockchain will consume lets say 1% of "capacity power" and for big ones almost zero.

The easiest way to achive that might be increasing time between blocks

It might be picking on, but implementing that will take relatively small effort

**Comment by wisepythagoras** [comment]
@oltarzewskik this is probably something that will be cleared up with the whitepaper. There won't be miners in the same way that they exist in the Bitcoin or Ethereum ecosystem, but rather a collection of nodes that share a common state.

Each block, much like Bitcoin, contains [a hash](https://github.com/wisepythagoras/dimoschain/blob/master/core/block.go#L21) (in this case it's SHA3-384). This can be used as a [seed to the pseudo-random byte generator](https://github.com/wisepythagoras/dimoschain/blob/master/crypto/prbg.go#L12), along with another attached value. By doing something like this and - of course - following certain rules (no double spending, minting rewards can't exceed limit, etc), nodes will be able to not only add new blocks to the chain, but also agree on what block to add without the threat of a fork.

This means that the same nodes that will receive the transactions, will also broadcast all of these transactions to other nodes and mint their own block, which will then be added to the chain.

Keep in mind that this is an over-simplified description of how this works.
